name: deploy

on:
  workflow_dispatch:

jobs:

  pypi:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - name: Package
        run: |
          pip install --index-url 'https://:2023-04-16@time-machines-pypi.sealsecurity.io/' --upgrade build hatchling==1.14.0
          python -m build -s -w --no-isolation
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pypi-dist
          path: dist/*
          if-no-files-found: error
